### PR TITLE
Fix ConcurrentModificationException with Magnesium

### PR DESCRIPTION
**Pull request by KitsuneAlex**

### CODE REVIEW

**Comment by KitsuneAlex** [comment]
I thought i might give a little explanation too after all.
The function from the cache class is usually called from only the render thread, but when Magensium or any other Sodium fork is present, that functions has be thread-safe, or rather, synchronized because otherwise a ConcurrentModificationException will be thrown. This does not affect regular functionality (without Magnesium installed) at all.
Cheers.

**Comment by ZeroNoRyouki** [comment]
Yup I get that, but the problem is Sodium / Magnesium / Hologen were not in the pack of the user that opened issue #5. That's what bothering me about this as a solution for that issue.

Setting aside #5, I concur on the need to syncronize that method with the possibility of Sodium being around. But loose the ConcurrentHashMap and revert it back to the original map since no two threads will access it at the same time now.

Thank you
Z

PS: bring back the this._cache in the constructor too please :)

**Comment by KitsuneAlex** [comment]
This wasn't meant to be a solution for that issue, it's the solution to a crash in my modpack, and that of some other people. I just thought the issues were related at first ^^ Also sure, but why have an unneeded this reference? o.o

**Comment by ZeroNoRyouki** [comment]
Ah now it make sense. You commented on that issue without mentioning the other crash so I was thinking it was only related to that issue.

Consistency with my coding style (an so with the rest of the mod code)

**Comment by KitsuneAlex** [comment]
Fair enough, imma change stuff to your liking and then you can merge. Thanks a bunch in advance ^^

**Comment by KitsuneAlex** [comment]
This should do it, i strongly recommend that you use FastUtil since it's in MC anyways.

**Comment by ZeroNoRyouki** [comment]
I actually use it quite a lot, but thank you for the suggestion anyway.

Blocks usually don't have a high number of models associated with them so change the actual map to an Int2ObjectArrayMap with an initial capacity of 16 as lookups will be faster and in greater numbers than additions. Also keep the field type a generic Int2ObjectMap. Or I could change things myself if you prefer.

Thank you
Z

**Pull request merged**
